name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GHCR
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/my-app:latest
        docker build -t $IMAGE_NAME -f docker/Dockerfile .

    - name: Push image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/my-app:latest
        docker push $IMAGE_NAME

    - name: Deploy on OpenShift
      run: |
        oc project myproject
        oc set image deploy/my-app my-app=ghcr.io/${{ github.repository_owner }}/my-app:latest
        oc rollout restart deploy/my-app
